sonar.projectName=norvii-web
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src,tests
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**/*.ts,tests/**/*.ts
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**
sonar.typescript.tsconfigPaths=tsconfig.app.json,tsconfig.node.json
