sonar.projectName=norvii-api
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=coverage.out,migrations/**
sonar.cpd.exclusions=cmd/**
sonar.coverage.exclusions=cmd/**,migrations/**
sonar.go.coverage.reportPaths=coverage.out
